apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: netraluis/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netraluis/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netraluis/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: netraluis/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: "**/*.js"
            dest: .
            